module Zuck
  class Insight < RawFbObject
    # https://developers.facebook.com/docs/marketing-api/insights/v2.4#fields
    #Koala::Facebook::ClientError: type: OAuthException, code: 100,
    # message: (#100) actions_per_impression, wesite_ctr are not valid for fields param. All valid values are:
    ## date_start, 
    ## date_stop, 
    ## account_id, 
    ## account_name, 
    ## adgroup_id, 
    ## adgroup_name, 
    ## buying_type, 
    ## campaign_group_id, 
    ## campaign_group_name, 
    ## campaign_id, 
    ## campaign_name, 
    ## action_carousel_card_id, 
    ## action_carousel_card_name, 
    ## actions, 
    ## unique_actions, 
    ## total_actions, 
    ## total_unique_actions, 
    ## action_values, 
    ## total_action_value, 
    ## impressions, 
    ## social_impressions, 
    ## clicks, 
    ## social_clicks, 
    ## unique_impressions, 
    ## unique_social_impressions, 
    ## unique_clicks, 
    ## unique_social_clicks, 
    ## spend, 
    ## frequency, 
    ## social_spend, 
    ## deeplink_clicks, 
    ## app_store_clicks, 
    ## website_clicks, 
    ## call_to_action_clicks, 
    ## newsfeed_avg_position, 
    ## newsfeed_impressions, 
    ## newsfeed_clicks, 
    ## reach, 
    ## social_reach, 
    ## ctr, 
    ## unique_ctr, 
    ## unique_link_clicks_ctr, 
    ## cpc, 
    ## cpm, 
    ## cpp, 
    ## cost_per_total_action, 
    ## cost_per_action_type, 
    ## cost_per_unique_click, 
    ## cost_per_10_sec_video_view, 
    ## cost_per_unique_action_type, 
    ## card_views, 
    ## relevance_score, 
    ## website_ctr, 
    ## video_avg_sec_watched_actions, 
    ## video_avg_pct_watched_actions, 
    ## video_p25_watched_actions, 
    ## video_p50_watched_actions, 
    ## video_p75_watched_actions, 
    ## video_p95_watched_actions, 
    ## video_p100_watched_actions, 
    ## video_complete_watched_actions, 
    ## video_10_sec_watched_actions, 
    ## video_15_sec_watched_actions, 
    ## video_30_sec_watched_actions, 
    ## estimated_ad_recallers, 
    ## estimated_ad_recallers_lower_bound, 
    ## estimated_ad_recallers_upper_bound, 
    ## estimated_ad_recall_rate, 
    ## estimated_ad_recall_rate_lower_bound, 
    ## estimated_ad_recall_rate_upper_bound
               # id fields
    known_keys :account_id,
               :adgroup_id,
               :campaign_id,
               :campaign_group_id,
               # date fields
               :date_start,
               :date_stop,
               # general fields
               :call_to_action_clicks,
               :clicks,
               :unique_clicks,
               :cost_per_total_action,
               :cpc,
               :cost_per_unique_click,
               :cpm,
               :cpp,
               :ctr,
               :unique_ctr,
               :frequency,
               :impressions,
               :reach,
               :relevance_score,
               :social_clicks,
               :unique_social_clicks,
               :social_impressions,
               :social_reach,
               :spend,
               :total_action_value,
               :total_actions,
               :total_unique_actions,
               # action and video fields
               :action_values,
               :actions,
               :cost_per_action_type
    parent_object :ad_campaign
    list_path :insights
  end
end
